{% set name = "koalas" %}
{% set version = "1.8.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 389b4be77fb1372a133e1d9bf826a03c3ac63d07a15ef716cd03da7037184415

build:
  number: 0
  script: '{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv '
  noarch: python

requirements:
  host:
    - pip
    - python >=3.5,<3.10
  run:
    - numpy >=1.14
    - pandas >=0.23.2
    - pyarrow >=0.10
    - python >=3.5,<3.10

test:
  requires:
    - pyspark >=2.4
  imports:
    - databricks
    - databricks.koalas
    - databricks.koalas.missing

about:
  home: https://github.com/databricks/koalas
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: pandas API on Apache Spark
  doc_url: https://koalas.readthedocs.io/
  dev_url: https://github.com/databricks/koalas

extra:
  recipe-maintainers:
    - rxin
    - thunterdb
    - gatorsmile
    - HyukjinKwon
    - ueshin
    - itholic
    - xinrong-databricks
