{% set name = "koalas" %}
{% set version = "0.19.0" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 08a77ecf5d32c1d80622a6963bd64ee02f2a8b71b5e11c81bf8079d055ed7591

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv "
  noarch: python

requirements:
  host:
    - pip
    - python >=3.5
  run:
    - matplotlib >=3.0.0
    - numpy >=1.14
    - pandas >=0.23.2
    - pyarrow >=0.10
    - python >=3.5

test:
  requires:
    - pyspark >=2.4
  imports:
    - databricks
    - databricks.koalas
    - databricks.koalas.missing

about:
  home: https://github.com/databricks/koalas
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: pandas API on Apache Spark
  doc_url: https://koalas.readthedocs.io/
  dev_url: https://github.com/databricks/koalas

extra:
  recipe-maintainers:
    - rxin
    - thunterdb
    - gatorsmile
    - HyukjinKwon
    - ueshin
