travis:
  secure:
    BINSTAR_TOKEN: oNbi8kZ5qUlM8adJsO4wBdTUVJ95dMfFTcIg/fZ93flDWz6YvbVeID0hoOPD9MvE4Lk+EHS1Vcp/Nc8MDTmonZ6LMoLzdpdqwyLbJmr+OEUlpxU8vY6J24Kx+DmBLicSaZ3SHu6w0Kb37a/npnOBd4DuGsrjrqF7cwKk7KeqUeOowqHUeT4VdnSStaF/Pa6TM62V8Obka1bJM/bYjIZaiDWfI4TKrrWbXzAreYqSmoWQHKNBVMMvX0DQ1CAAKirN8m1urEOXqeeZj+bjJdsg/baTOgnyf4VNA81it4DJT0WaTsqHyNNe500LPk8mwKoU3t68vnattWMnWpNdPZfiJUJnxG5Vp4PLx7af+mbD29w/Zk/oYeqEuVjd0o4vrW7FYztwezyc9N2BViUe/7h2RlwWUui8SmJwfFZTU5unNiGQ8YOwTbdnDDiQMM884cGkB/Vk5xggKFE6v27VDl1xsptW/xDfNBS2xhAEqksnhtUvw9712Y8QBXEc8KWU+p04MyE4yc4ktRbpM3DOOCBnVMV5C9rQ25wt7SaiM5b3Un8kjmAn+MzTCD9vAxZ+1A3pSLK1gy/L5Mnpdyw1wYes5XJ09MuV1ceUpGVtUlCfJrCghRsqghMYKAbtti40tGjG+vrsaYfUG474J9CDWqI8x1qGd/irCK8Q4t/UFLq5S5A=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
